default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: paul
  password:

development:
  <<: *default
  database: painter_dev

test:
  <<: *default
  database: painter_test

production:
  <<: *default
  database: painter_prod
